DEFAULT_CONFIG_LOCATION = "%s/../setup.conf"

CONFIG_RETRIEVAL = "retrieval"
CONFIG_RETRIEVAL_LOG_DATABASE = "log"
CONFIG_RETRIEVAL_PERIOD = "period"
CONFIG_RETRIEVAL_SINCE = "since"

CONFIG_COOKIEJAR = "cookiejar"
CONFIG_COOKIEJAR_HOST = "host"
CONFIG_COOKIEJAR_PORT = "port"
CONFIG_COOKIEJAR_DATABASE = "database"

CONFIG_PROCESSING = "processing"
CONFIG_PROCESSING_PROCESSORS = "processors"
CONFIG_PROCESSING_RULES = "rules"
CONFIG_PROCESSING_NOTIFICATION_RECEIVERS = "notification_receivers"
CONFIG_PROCESSING_ENRICHMENT_LOADERS = "enrichment_loaders"

CONFIG_API = "api"
CONFIG_API_PORT = "port"

CONFIG_BATON = "baton"
CONFIG_BATON_BINARIES_LOCATION = "bin"
CONFIG_BATON_ZONE = "zone"
